CREATE TABLE EMPLOYEES 
   (	EMPLOYEE_ID NUMERIC(6,0) PRIMARY KEY, 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(25), 
	EMAIL VARCHAR(25), 
	PHONE_NUMBER VARCHAR(20), 
	HIRE_DATE DATE, 
	JOB_ID VARCHAR(10), 
	SALARY NUMERIC(8,2), 
	COMMISSION_PCT NUMERIC(2,2), 
	MANAGER_ID NUMERIC(6,0), 
	DEPARTMENT_ID NUMERIC(4,0)
   )
   
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
